### ISSUE TITLE
(Recommendation)

### ISSUE THREAD

**Issue by SmugTheKiler** [botlists/issues#2]
Umm, I recommend on the webhooks to Discord, in the embed, tell from which bot list the vote is coming from, since I have like 15 other bot lists voting webhooks on one...

**Comment by sell** [comment]
Will fix, thanks for this.

**Comment by sell** [comment]
Has been fixed to do so.

![image](https://user-images.githubusercontent.com/34258275/132113735-f34bd548-c636-4bb5-bbb6-8653e16c294f.png)
