### ISSUE TITLE
Found bug:

### ISSUE THREAD

**Issue by RobloxGithub** [botlists/issues#5]
"Now bot is not updating vote count if someone votes webhook is sending the same embed and shows that user who voted before and not updating"

**Comment by sell** [comment]
Fixed with https://github.com/botlists/bot-list-api/commit/ca77a96cffe327b0e11ae590d5a6d12dfc38f937

Thanks 🚀

**Comment by RobloxGithub** [comment]
what THE FUCK I DIDN'T GAVE YOU MY E-MAIL

pet, 5. stu 2021. 07:20 Jay ***@***.***> je napisao:
